library(shiny)
library(shinydashboard)
library(CountOpsLogan) # remotes::install_github('kent37/CountOpsLogan')
library(dplyr)
library(ggplot2)
library(glue)
library(lubridate)
library(rlang)
library(silgelib)
library(stringr)
library(tidyr)
library(zoo)

all_data = countops_hourly
runways = sort(unique(all_data$Runway))
